### ISSUE TITLE
DOCS - Please explain more from CPP Side

### ISSUE THREAD

**Issue by TimSusa** [jazz-soft/midi-test#1]
Hey, 

as this project helped a lot to establish browserless tests for the webmidi project (big thx for your help!), I noticed the cpp-code here is not really documented. I come from a CPP Background but without any docu at all, it is hard to find a way through it and maybe you could help to explain the Cpp more in detail? Maybe you could put some more info to the README on what each module does?

Another question that I have, do you think it is enough to write tests in javascript, to test code, which stems from CPP? I mean i am not really sure about this, because node-gyp does a lot of things in between, that I am not capable of. 

Thanks in advance and again thanks for your input to webmidi.

**Comment by jazz-soft** [comment]
Every project could be improved when you have enough budget :)
But currently, I have more urgent tasks related to my MIDI projects.
As for the testing, since the product offers very few and very simple features, I believe that javascript tests are adequate.
